import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guess the Painting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} mx-auto flex min-h-screen max-w-[512px] flex-col items-center justify-center px-2 tablet:px-0`}
      >
        <h1 className="text-2xl font-medium">Guess the Painting</h1>
        {children}
      </body>
    </html>
  );
}
