import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import type { Metadata } from "next";
import { Inter, Playfair } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const playFair = Playfair({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fairplay",
});

export const metadata: Metadata = {
  title: "Guess the Painting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${playFair.variable} mainBackground mx-auto flex min-h-screen flex-col items-center justify-center px-2 py-6`}
      >
        <div className="flex w-[600px] flex-col items-center justify-center">
          <Header />
          <div className="cardBackground border-brown-main flex h-[90vh] w-[600px] flex-col items-center justify-center rounded-lg border-2 px-4 py-10 shadow-2xl">
            <div className="flex h-full flex-col items-center justify-start rounded-lg">
              {children}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
